//-- LOADING --//
export const END_LOADING = 'END_LOADING';
export const START_LOADING = 'START_LOADING';

//-- USER AUTH --//
export const USER_SIGNIN = 'USER_SIGNIN'
export const USER_SIGNUP = 'USER_SIGNUP'
export const USER_SIGNOUT = 'USER_SIGNOUT'

//-- POST --//
export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_TIMELINE = 'FETCH_TIMELINE'
export const FETCH_SINGLE_POST = 'FETCH_SINGLE_POST'
export const FETCH_PROFILE_POSTS = 'FETCH_PROFILE_POSTS'
export const CREATE_POST = 'CREATE_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'
export const POST_LIKES = 'POST_LIKES'
export const COMMENT_POST = 'COMMENT_POST'

//-- USERS --//
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS'
export const FETCH_FRIENDS_LIST = 'FETCH_FRIENDS_LIST'
//export const FETCH_FRIENDS_OTHER_PROFILE = 'FETCH_FRIENDS_OTHER_PROFILE'
// export const FOLLOW_FRIEND = 'FOLLOW_FRIEND'
export const GET_USER = 'GET_USER'
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS'
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE'
export const UPDATE_COVER_IMG = 'UPDATE_COVER_IMG'


//-- ADMIN ACTIONS --//
export const DELETE_USER = 'DELETE_USER'
export const FETCH_ALL_USERS_ADMIN = 'FETCH_ALL_USERS_ADMIN'
export const TOGGLE_MODERATOR = 'TOGGLE_MODERATOR'
export const GET_ALL_POSTS_ADMIN = 'GET_ALL_POSTS_ADMIN'
//-- SEARCH --//
export const SEARCH_FILTER = 'SEARCH_FILTER'